# Generated by Django 4.2.27 on 2026-01-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='workers', to='core.service'),
        ),
    ]
