# Generated by Django 4.2.27 on 2026-01-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='commitments',
            field=models.TextField(blank=True, help_text='Our commitments to the customer', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='whats_included',
            field=models.TextField(blank=True, help_text="What's included in the service", null=True),
        ),
    ]
