# Generated by Django 4.2.27 on 2026-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='commitments',
        ),
        migrations.RemoveField(
            model_name='service',
            name='whats_included',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_STATUS', 'Booking Status'), ('ASSIGNMENT', 'Assignment'), ('OTP', 'OTP'), ('PAYMENT', 'Payment'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
