# Generated by Django 4.2.27 on 2026-01-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
