# Generated by Django 4.2.27 on 2026-01-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='included_items',
            field=models.TextField(blank=True, help_text='JSON array of items included in the service', null=True),
        ),
    ]
