# Generated by Django 4.2.27 on 2026-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service_included_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_STATUS', 'Booking Status'), ('ASSIGNMENT', 'Assignment'), ('OTP', 'OTP'), ('PAYMENT', 'Payment'), ('SYSTEM', 'System'), ('BOOKING_REJECTION', 'Booking Rejection')], max_length=20),
        ),
    ]
