# Generated by Django 4.2.27 on 2026-01-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='suggested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='suggested_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
