# Generated by Django 4.2.27 on 2026-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_booking_suggested_date_booking_suggested_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('REACHED', 'Reached'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DELAYED', 'Delayed')], default='PENDING', max_length=20),
        ),
    ]
